aiapps/aiapps/urls.py
from django.contrib import admin
from django.urls import path, include
# import catdog.views as carbike

urlpatterns = [
    path('admin/', admin.site.urls),
    path('catdog/', include('catdog.urls')),
]

aiapps/catdog/urls.py
from os import name
from catdog.views import predict, true_result, false_result 
from django.urls import path

from . import views

app_name = 'catdog'
urlpatterns = [
    path('', views.index, name='index'),
    path('predict/', views.predict, name='predict'),
    path('true/', views.true_result, name='true'),
    path('false/', views.false_result, name='false'),
]

aiapps/catdog/models.py
from django.db import models
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import load_model
from PIL import Image
import sys
import io, base64

graph = tf.compat.v1.get_default_graph()
# graph = tf.get_default_graph()

class Photo(models.Model):
    image = models.ImageField(upload_to='photos')

    IMAGE_SIZE = 224
    MODEL_FILE_PATH = './catdog/ml_models/vgg16_transfer.h5'
    classes = ['cat', 'dog']
    num_classes = len(classes)

    def predict(self):
        model = None
        global graph
        with graph.as_default():
        # model = load_model(self.MODEL_FILE_PATH)
            model = load_model(self.MODEL_FILE_PATH)

            img_data = self.image.read()
            img_bin = io.BytesIO(img_data)

            image = Image.open(img_bin)
            image = image.convert("RGB")
            image = image.resize((self.IMAGE_SIZE, self.IMAGE_SIZE))
            data = np.asarray(image) / 255.0
            X = []
            X.append(data)
            X = np.array(X)

            result = model.predict([X])[0]
            predicted = result.argmax()
            percentage = int(result[predicted] * 100)

            # print(self.classes[predicted], percentage)
            return  self.classes[predicted], percentage

    def image_src(self):
        with self.image.open() as img:
            base64_img = base64.b64encode(img.read()).decode()

            return 'data:' + img.file.content_type + ';base64,' + base64_img

aiapps/catdog/forms.py
from django import forms

class PhotoForm(forms.Form):
    image = forms.ImageField(widget=forms.FileInput(attrs={'class':'custom-file-input'}))

aiapps/catdog/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from django.template import loader
from .forms import PhotoForm
from .models import Photo

def index(request):
    template = loader.get_template('catdog/index.html')
    context = {'form':PhotoForm()}
    return HttpResponse(template.render(context, request))

def predict(request):
    if not request.method == 'POST':
        return
        redirect('catdog.index')

    print('check')
    form = PhotoForm(request.POST, request.FILES)
    if not form.is_valid():
        raise ValueError('Formが不正です')

    photo = Photo(image=form.cleaned_data['image'])
    predict, percentage = photo.predict()

    template = loader.get_template('catdog/predict.html')
    context = {
        'photo_name': photo.image.name,
        'photo_data': photo.image_src(),
        'predicted': predict,
        'percentage': percentage,
    }
    return HttpResponse(template.render(context, request))

def true_result(request):
    return render(request, 'catdog/true_results.html')

def false_result(request):
    return render(request, 'catdog/false_results.html')

aiapps/catdog/templates/catdog/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% load static %}
    {% load bootstrap4 %}
    {% bootstrap_css %}
    <link rel="stylesheet" type="text/css" href="{% static 'catdog/css/style.css' %}">
    {% bootstrap_javascript jquery='full' %}
    <title>犬・猫 判定 | {% block title %}{% endblock %}</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="#">画像判定AIアプリ</a>
    </nav>
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</body>


</html>

aiapps/catdog/templates/catdog/false_results.html
{% extends 'catdog/base.html' %}

{% block content %}
    {% load static %}
    <a><img src="{% static "photo/business_woman1_3_cry.png" %}"></a>
<p>不正解で残念、、よかったらまた遊んでね！</p>
    <a href="{% url 'catdog:index' %}" class="btn btn-primary">画像選択メニューに戻る</a>
{% endblock %}

aiapps/catdog/templates/catdog/index.html
{% extends 'catdog/base.html' %}
{% block titile %}猫・犬の推定アプリメニュー{% endblock %}

{% block content %}
<div>
    <h4 class="mt-4 mb-5 border-bottom">猫・犬の推定アプリ</h4>
    <p>画像ファイルを選択して推定ボタンを押してください</p>
    <form action="{% url 'catdog:predict' %}" method="post" class="form" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <div class="custom-file">
                {{ form.image }}
                <label class="custom-file-label" form="customFile">
                    推定したいファイルを選択してください
                </label>
            </div>
        </div>
        <button type="submit" class="btn btn-primary">推定する</button>
    </form>
</div>
{% endblock %}

aiapps/catdog/templates/catdog/predict.html
{% extends 'catdog/base.html' %}
{% block titile %}猫・犬の推定結果{% endblock %}

{% block content %}
<div>
    <h4 class="mt-4 mb-5 border-bottom">猫・犬推定アプリ</h4>

    <table class="table">
        <tbody>
             <tr>
                <td>ファイル名</td>
                <td>{{ photo_name }}</td>
        </tr>
             <tr>
                <td>画像ファイル</td>
                 <td><img class="preview-img" src={{ photo_data }}></img></td>
            </tr>
             <tr>
                <td>推定ラベル</td>
                <td>{{ predicted }}</td>
            </tr>
            <tr>
                <td>推定確率</td>
                <td>{{ percentage }} %</td>
            </tr>

        </tbody>
    </table>

    <a href="{% url 'catdog:true' %}" class="btn btn-success">正解</a>
    <a href="{% url 'catdog:false' %}" class="btn btn-danger">不正解</a>
</div>
{% endblock %}

aiapps/catdog/templates/catdog/true_results.html
{% extends 'catdog/base.html' %}

{% block content %}
    {% load static %}
    <a><img src="{% static "photo/business_woman1_4_laugh.png" %}"></a>
<p>正解してよかったです！また遊んでね！</p>
    <a href="{% url 'catdog:index' %}" class="btn btn-primary">画像選択メニューに戻る</a>
{% endblock %}